/*
 * proto/v1beta1/project.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.grafeas.api;

import io.grafeas.ApiException;
import io.grafeas.model.ProjectListProjectsResponse;
import io.grafeas.model.ProjectProject;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectsApi
 */
@Ignore
public class ProjectsApiTest {

    private final ProjectsApi api = new ProjectsApi();

    /**
     * Creates a new project.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProjectTest() throws ApiException {
        ProjectProject body = null;
        ProjectProject response = api.createProject(body);

        // TODO: test validations
    }
    /**
     * Deletes the specified project.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectTest() throws ApiException {
        String name = null;
        Object response = api.deleteProject(name);

        // TODO: test validations
    }
    /**
     * Gets the specified project.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectTest() throws ApiException {
        String name = null;
        ProjectProject response = api.getProject(name);

        // TODO: test validations
    }
    /**
     * Lists projects.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProjectsTest() throws ApiException {
        String filter = null;
        Integer pageSize = null;
        String pageToken = null;
        ProjectListProjectsResponse response = api.listProjects(filter, pageSize, pageToken);

        // TODO: test validations
    }
}
