/*
 * proto/v1beta1/project.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.grafeas.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.grafeas.model.ProjectProject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Response for listing projects.
 */
@Schema(description = "Response for listing projects.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-14T12:08:59.914-07:00[America/Los_Angeles]")public class ProjectListProjectsResponse {

  @SerializedName("projects")
  private List<ProjectProject> projects = null;

  @SerializedName("next_page_token")
  private String nextPageToken = null;
  public ProjectListProjectsResponse projects(List<ProjectProject> projects) {
    this.projects = projects;
    return this;
  }

  public ProjectListProjectsResponse addProjectsItem(ProjectProject projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<ProjectProject>();
    }
    this.projects.add(projectsItem);
    return this;
  }

  /**
  * The projects requested.
  * @return projects
  **/
  @Schema(description = "The projects requested.")
  public List<ProjectProject> getProjects() {
    return projects;
  }
  public void setProjects(List<ProjectProject> projects) {
    this.projects = projects;
  }
  public ProjectListProjectsResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  

  /**
  * The next pagination token in the list response. It should be used as &#x60;page_token&#x60; for the following request. An empty value means no more results.
  * @return nextPageToken
  **/
  @Schema(description = "The next pagination token in the list response. It should be used as `page_token` for the following request. An empty value means no more results.")
  public String getNextPageToken() {
    return nextPageToken;
  }
  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectListProjectsResponse projectListProjectsResponse = (ProjectListProjectsResponse) o;
    return Objects.equals(this.projects, projectListProjectsResponse.projects) &&
        Objects.equals(this.nextPageToken, projectListProjectsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(projects, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectListProjectsResponse {\n");
    
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
